services:
  - type: web
    name: blogify
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: node app.js
    envVars:
      - key: PORT
        fromEnvVar: PORT
      - key: MONGO_URL
        fromEnvVar: MONGO_URL
      - key: SECRET
        fromEnvVar: SECRET
      - key: CLOUDINARY_CLOUD_NAME
        fromEnvVar: CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
        fromEnvVar: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
        fromEnvVar: CLOUDINARY_API_SECRET
